StringTableRuntime {
 Ids {
  "AAX_JTAC_BACKPACK_DESCRIPTION"
  "AAX_JTAC_BACKPACK_NAME"
  "AAX_M713_NAME"
  "AAX_M715_NAME"
  "AAX_M716_NAME"
 }
 Texts {
  "Radio backpack for with inventory"
  "JTAC Radio Backpack"
  "40mm Smoke Red"
  "40mm Smoke Green"
  "40mm Smoke Yellow"
 }
}