StringTable {
 ItemClassName "DefaultStringTableItem"
 Items {
  DefaultStringTableItem "{69A6EDC40E94EC20}" {
   Id "AAX_JTAC_BACKPACK_DESCRIPTION"
   Target_en_us "Radio backpack for with inventory"
  }
  DefaultStringTableItem "{69A6EDC41B6041D2}" {
   Id "AAX_JTAC_BACKPACK_NAME"
   Target_en_us "JTAC Radio Backpack"
  }
  DefaultStringTableItem "{69A5380F62378040}" {
   Id "AAX_M713_NAME"
   Target_en_us "40mm Smoke Red"
  }
  DefaultStringTableItem "{69A5380F5AC3982F}" {
   Id "AAX_M715_NAME"
   Target_en_us "40mm Smoke Green"
  }
  DefaultStringTableItem "{69A5380F4C1C0BB4}" {
   Id "AAX_M716_NAME"
   Target_en_us "40mm Smoke Yellow"
  }
 }
}