SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 m_CallsignInfo SCR_FactionCallsignInfo "{5DA0F2A6677ADA9E}" {
  m_aPlatoonNames {
   SCR_CallsignInfo "{55CCB792CE18FB44}" {
   }
  }
 }
 m_aPredefinedGroups {
  SCR_GroupPreset "{6960E5F269C50245}" {
   m_sGroupName "Atlas 1-1 "
   m_eGroupRole ASSAULT
   m_sGroupFlag "{7C00FED5562A84D3}UI/icons/Atlas1-1.edds"
   m_iGroupSize 20
   m_iRadioFrequency 38000
   m_iDefaultActiveRadioChannel 45000
   m_bIsPrivacyChangeable 0
  }
  SCR_GroupPreset "{698AFEA17C6A48D1}" {
   m_sGroupName "Atlas 1-0"
   m_eGroupRole COMMANDER
   m_sGroupDescription "Atlas 1-0"
   m_iGroupSize 20
   m_iRadioFrequency 45000
   m_iDefaultActiveRadioChannel 48000
  }
  SCR_GroupPreset "{6960E5F242636D4B}" {
   m_sGroupName "Atlas 1-2"
   m_eGroupRole ASSAULT
   m_sGroupFlag "{22E8D796E9A70ADC}UI/icons/Atlas1-2.edds"
   m_iGroupSize 20
   m_iRadioFrequency 40000
   m_iDefaultActiveRadioChannel 45000
   m_bIsPrivacyChangeable 0
  }
  SCR_GroupPreset "{6960E5F2A63F5931}" {
   m_sGroupName "STRIX"
   m_eGroupRole HELI_TRANSPORT
   m_sGroupFlag "{1B24116250505E8F}UI/icons/STRIX.edds"
   m_iGroupSize 20
   m_iRadioFrequency 69000
   m_iDefaultActiveRadioChannel 48000
   m_bIsPrivacyChangeable 0
  }
  SCR_GroupPreset "{6960E5F28AC45B78}" {
   m_sGroupName "Atlas HQ"
   m_eGroupRole COMMANDER
   m_sGroupFlag "{303A905AC6CADFAB}UI/icons/HQ.edds"
   m_iGroupSize 20
   m_iRadioFrequency 48000
   m_iDefaultActiveRadioChannel 48000
   m_bIsPrivacyChangeable 0
  }
  SCR_GroupPreset "{6969114825D2CCA2}" {
   m_sGroupName "REME"
   m_eGroupRole MECHANIZED
   m_sGroupFlag "{AE411525E5FB98E7}UI/icons/reme.edds"
   m_iGroupSize 20
   m_iRadioFrequency 48000
   m_iDefaultActiveRadioChannel 48000
   m_bIsPrivacyChangeable 0
  }
 }
 m_bEnableAutoGroupCreationWhenFull 0
}