SCR_MissionHeader {
 World "{CBE0FD098832786B}Worlds/1AAX Kunar.ent"
 m_sName "1AAX Kunar Province"
 m_sAuthor "Dodrio3"
 m_sDescription "A Varation Of Kunar Province Built for 1st Air Assult Brigade Campaign Missions"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}