SCR_MissionHeader {
 World "{B632FB64256ECAA3}Worlds/Second.ent"
 SystemsConfig "{8DDC2A311929D52F}Configs/Systems/GameMasterSystems.conf"
 m_sName "Silent Dune"
 m_sAuthor "Convexmussel"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
}